### PR TITLE
REAME.md Changes

### PR DESCRIPTION
**Pull request by KyleStilkey**
Update and added lots of troubleshooting steps to try and help users out with any trouble they may have.

### CODE REVIEW

**Comment by KyleStilkey** [comment]
I hope I did this all correct as I've never in the life of me submitted a Pull Request

**Comment by KyleStilkey** [comment]
I'm just putting this here as of a note so depending if this is what you want or something else I can update it later, but Devices not showing up bug and clearing CMOS/Power Cycle needs to be added. I'll know what is needed once I know how you would like this done as this may also be another reason why people think it's not working as I just spent the last 8 hours figuring this one out.

**Comment by AndrewBabbitt97** [comment]
That issue with devices not showing up is usually a race condition, my software starting up before AURA has fully initialized.

I honestly want to look into that more, there's another PR open related to this very thing that I need to look into more.

It's all kinda ugly how it works for waiting for Aura, but there's not a ton of good options as the Aura SDK has no way of notifying me of when it's ready to go. If you start using it early you won't get all the devices.

I may be able to add a watcher to monitor the device list for new devices, but I think this may be an expensive CPU operation and I don't want to do it often if I can avoid it which is why we only do it once at startup.

**Comment by KyleStilkey** [comment]
There's an issue with Aura itself and communication with motherboards sometimes that a computer crash can cause this and clearing out the CMOS seems to be the only fix that I've been able to fine. I have no idea why but it just loses the ability to see the motherboard and the lights will just run the default settings or just freeze on the last color seen.

I also believe that the new Armour is now busted for some users including me as reports are flying in and I've got a few systems with issues of either it just not working anymore or the worst is the colors just freak out like crazy or freezes randomly on a color. 

Also have a few systems still with the services not starting up so there is still some conflicts going on and more reports are coming in on Aura for this as well. 

A majority of the problem really just stem down to ASUS really, and either waiting on them to actually fix these problems or even better dumping it and open sourcing it would be way better but I don't see that happening anytime soon.

**Comment by AndrewBabbitt97** [comment]
99% of issues that come through are indeed related to ASUS and not this software. To date I have only had to make 2 code changes because of bugs.

Probably need to get some issue templates in that ensures people have checked through the well known issues and existing issues before opening a new issue.

**Comment by AndrewBabbitt97** [comment]
FYI: Avoid over usage of caps for documentation, first letter is generally good enough. Whole words leads to things looking bad. "ASUS Aura" instead of "ASUS AURA" (also how ASUS themselves types it) and headers using title case.

Thanks for the work, Ill be cleaning up the readme soon.

**Pull request merged**
